name: Build and Release GLOS

on:
  push:
    branches:
      - main  # Triggers when merging a release into main
  pull_request:
    branches:
      - dev  # Runs tests on dev and feature branches
  workflow_dispatch:  # Allows manual triggering

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libglfw3-dev libwayland-dev libxkbcommon-dev libxrandr-dev libxi-dev libudev-dev libxcursor-dev

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'  # Adjust to your Go version

      - name: Run tests
        run: go test ./...  # Make sure you have tests in place!

  release:
    name: Build and Release
    runs-on: ubuntu-latest
    needs: test  # Runs only if tests pass
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libglfw3-dev libwayland-dev libxkbcommon-dev libxrandr-dev libxi-dev libudev-dev


      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build binary
        run: |
          go build -o glos main.go  # Change output name if needed

      - name: Archive binary
        run: |
          tar -czvf glos-linux-amd64.tar.gz glos
          echo "VERSION=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.VERSION }}
          name: "Release ${{ env.VERSION }}"
          body: "Auto-generated release for version ${{ env.VERSION }}"
          draft: false
          prerelease: true  # Mark as a pre-release if it's below 1.0.0
          files: glos-linux-amd64.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
